name: build

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  build-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.5
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.5'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip build
    - name: Build package
      run: python -m build
    - name: Debug Secrets
      run: |
        echo "PYPI_API_TOKEN length: ${#PYPI_API_TOKEN}"
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
